from ._version import __version__

from ._global import logger, configure_logging

from ._exceptions import (
    SwiftCompLicenseError,
    VABSLicenseError,
    SwiftCompIOError,
    VABSIOError,
    SwiftCompError,
    VABSError,
    OutputFileError,
)

from .core import (
    FEModel,
    Orientation,
    SGAnalysisConfig,
    Section,
    StructureGene,
    StructuralModel,
    SGMesh,
    check_isolated_nodes,
    renumber_elements,
    validate_node_ids,
    validate_element_ids,
    get_node_id_mapping,
    ensure_node_ids,
    ensure_element_ids,
    auto_renumber_for_format,
    check_duplicate_ids,
    check_forbidden_ids,
    FormatNumberingRequirements,
    FORMAT_ALIASES,
    FORMAT_REQUIREMENTS,
    normalize_format_name,
    get_numbering_requirements,
)
from .core.builder import build_sg_1d
from .core.merge import combine_sg

from .model import (
    BehaviorVariable,
    BehaviorVariableRole,
    CauchyContinuumModel,
    ChannelBehaviorSlot,
    ChannelCouplingDescriptor,
    ConstitutiveBehaviorDescriptor,
    ConstitutiveBehaviorProtocol,
    ElasticInputType,
    EulerBernoulliBeamModel,
    HistoryDependentBehaviorProtocol,
    KirchhoffLovePlateShellModel,
    LinearElasticConstitutiveBehavior,
    LocationType,
    MaterialBehaviorMap,
    MatrixKind,
    Model,
    PhysicsChannel,
    ReissnerMindlinPlateShellModel,
    SectionAxis,
    SectionCenter,
    SectionMatrixKind,
    State,
    StateCase,
    TensorComponent,
    TimoshenkoBeamModel,
    getModelDim,
)

from .iofunc import (
    read,
    read_fe_model,
    read_output,
    read_output_model,
    read_output_state,
    read_config_from_json,
    read_material_from_json,
    read_materials_from_json,
    read_sections_from_json,
    read_sg_from_gmsh_bundle,
    section_model_to_record,
    write,
    convert,
    merge_sections,
    merge_sections_from_csv,
    read_load_csv,
    read_section_layout_csv,
    write_config_to_json,
    write_material_to_json,
    write_sections_to_json,
    write_merged_sections,
    add_cell_dict_data_to_mesh,
    add_point_dict_data_to_mesh,
    # write_points_cells,
    # register_format,
    # deregister_format,
    # extension_to_filetypes,
    # sg_reader_map,
    # sg_writer_map,
    # overridden_formats
)

from .execu import run

from .visualization import (
    create_pyvista_local_axis_multiblock,
    create_pyvista_plotter,
    plot_sg_pyvista,
    plot_pyvista_local_axes,
    plot_matrix,
    plot_matrix_bar3d,
    plot_model_matrix,
    plot_sg_matplotlib,
    plot_sg_plotly,
    plot_sg_2d,
    plot_model_2d,
    plot_sg_2d_plotly,
    plot_model_2d_plotly,
    plot_sg_3d_beam,
    plot_sg_3d_beam_plotly,
)

from ._vendors import inprw

__all__ = [
    # Version
    "__version__",
    # Configuration and logging
    "configure_logging",
    # I/O functions
    "read",
    "read_fe_model",
    "read_output",
    "read_output_model",
    "read_output_state",
    "write",
    "convert",
    "read_load_csv",
    "merge_sections",
    "merge_sections_from_csv",
    "read_section_layout_csv",
    "read_sg_from_gmsh_bundle",
    "read_sections_from_json",
    "write_sections_to_json",
    "read_config_from_json",
    "read_material_from_json",
    "read_materials_from_json",
    "write_material_to_json",
    "write_config_to_json",
    "section_model_to_record",
    "write_merged_sections",
    "add_cell_dict_data_to_mesh",
    "add_point_dict_data_to_mesh",
    # Execution
    "run",
    # Core functions and classes
    "build_sg_1d",
    "combine_sg",
    "FEModel",
    "Orientation",
    "SGAnalysisConfig",
    "SGMesh",
    "Section",
    "StructureGene",
    "StructuralModel",
    "check_isolated_nodes",
    "renumber_elements",
    # Numbering validation and utilities
    "validate_node_ids",
    "validate_element_ids",
    "get_node_id_mapping",
    "ensure_node_ids",
    "ensure_element_ids",
    "auto_renumber_for_format",
    "check_duplicate_ids",
    "check_forbidden_ids",
    # Format requirements registry (Phase 4.1)
    "FormatNumberingRequirements",
    "FORMAT_ALIASES",
    "FORMAT_REQUIREMENTS",
    "normalize_format_name",
    "get_numbering_requirements",
    # Visualization functions
    "create_pyvista_local_axis_multiblock",
    "create_pyvista_plotter",
    "plot_sg_pyvista",
    "plot_pyvista_local_axes",
    "plot_matrix",
    "plot_matrix_bar3d",
    "plot_model_matrix",
    "plot_sg_matplotlib",
    "plot_sg_plotly",
    "plot_sg_2d",
    "plot_model_2d",
    "plot_sg_2d_plotly",
    "plot_model_2d_plotly",
    "plot_sg_3d_beam",
    "plot_sg_3d_beam_plotly",
    # Model classes from .model import *
    "BehaviorVariable",
    "BehaviorVariableRole",
    "CauchyContinuumModel",
    "ChannelBehaviorSlot",
    "ChannelCouplingDescriptor",
    "ConstitutiveBehaviorDescriptor",
    "ConstitutiveBehaviorProtocol",
    "ElasticInputType",
    "EulerBernoulliBeamModel",
    "HistoryDependentBehaviorProtocol",
    "KirchhoffLovePlateShellModel",
    "LinearElasticConstitutiveBehavior",
    "LocationType",
    "MaterialBehaviorMap",
    "MatrixKind",
    "Model",
    "PhysicsChannel",
    "ReissnerMindlinPlateShellModel",
    "SectionAxis",
    "SectionCenter",
    "SectionMatrixKind",
    "State",
    "StateCase",
    "TensorComponent",
    "TimoshenkoBeamModel",
    "getModelDim",
    # Exception classes
    "SwiftCompLicenseError",
    "VABSLicenseError",
    "SwiftCompIOError",
    "VABSIOError",
    "SwiftCompError",
    "VABSError",
    "OutputFileError",
]
