from math import atan2, cos, radians, sin, sqrt
import numpy as np


def skew_symmetric_matrix(v):
    r"""
    Compute the skew symmetric matrix of a 3x1 vector.

    Parameters
    ----------
    v : array-like
        3x1 vector

    Returns
    -------
    vtilde : array
        3x3 skew symmetric matrix

    Examples
    --------
    >>> v = [0, 0, 1]
    >>> vtilde = skew_symmetric_matrix(v)
    >>> vtilde
    array([[0, -1, 0],
           [1, 0, 0],
           [0, 0, 0]])
    """
    if v is None:
        raise ValueError("Input argument `v` cannot be None.")

    try:
        v0, v1, v2 = v
    except (ValueError, TypeError):
        raise ValueError("Input argument `v` must be a 3x1 vector.")

    vtilde = np.zeros((3, 3))

    vtilde[0, 1] = -v2
    vtilde[0, 2] = v1
    vtilde[1, 0] = v2
    vtilde[1, 2] = -v0
    vtilde[2, 0] = -v1
    vtilde[2, 1] = v0

    return vtilde




def calc_rotation_tensor_from_parameters(rotation_parameters, method=''):
    r"""Calculate rotation tensor from rotation parameters.

    Parameters
    ----------
    rotation_parameters : array_like
        Rotation parameters (3x1).
    method : str
        Rotation parameter type.

        * `er` - Eular-Rodrigues
        * `wm` - Wiener-Milenkovic

    Returns
    -------
    rotation_tensor : array_like
        Rotation tensor (3x3)

    Examples
    --------
    >>> rotation_parameters = [0, 0, np.pi/2]
    >>> rotation_tensor = calc_rotation_tensor_from_parameters(rotation_parameters, method='er')
    >>> np.allclose(rotation_tensor, [[0, -1, 0], [1, 0, 0], [0, 0, 1]])
    True
    """

    if rotation_parameters is None:
        raise ValueError("Input argument `rotation_parameters` cannot be None.")

    rotation_parameters = np.array(rotation_parameters)

    if method == 'er':
        # Eular-Rodrigues
        rotation_tensor = (
            np.eye(3) - 0.5 * skew_symmetric_matrix(rotation_parameters)
            + np.dot(
                skew_symmetric_matrix(rotation_parameters),
                skew_symmetric_matrix(rotation_parameters)
            ) / (1 + np.dot(rotation_parameters, rotation_parameters))
        )
    elif method == 'wm':
        # Wiener-Milenkovic
        c0 = 2 - np.dot(rotation_parameters, rotation_parameters) / 8
        rotation_tensor = (
            (c0**2 - np.dot(rotation_parameters, rotation_parameters)) * np.eye(3)
            - 2 * c0 * skew_symmetric_matrix(rotation_parameters)
            + 2 * np.outer(rotation_parameters, rotation_parameters)
        ) / (4 - c0)**2
    else:
        raise ValueError("Input argument `method` is not supported.")

    return rotation_tensor




def floor_absolute(value):
    r"""Floor the value towards negative infinity, clamping near-zero values to 0.

    Parameters
    ----------
    value : float
        Value to be rounded.

    Returns
    -------
    float
        Floored value

    Examples
    --------
    >>> floor_absolute(0.7)
    0.0
    >>> floor_absolute(-0.7)
    -1.0
    >>> floor_absolute(0.0)
    0.0
    """
    if value is None:
        raise ValueError("Input argument `value` cannot be None.")
    if value > 1e-15:
        # Positive
        return np.floor(value)
    elif value < -1e-15:
        # Negative
        return np.floor(value)
    else:
        # Very close to 0
        return 0.0




def angle_to_cosine_2d(angle_degrees):
    r"""
    Convert an angle in degrees to a 2x2 cosine matrix.

    Parameters
    ----------
    angle_degrees : float
        Angle in degrees to be converted.

    Returns
    -------
    cosine_matrix : list of lists
        2x2 cosine matrix

    Examples
    --------
    >>> angle_to_cosine_2d(45)
    [[0.7071067811865476, -0.7071067811865476],
     [0.7071067811865476, 0.7071067811865476]]
    """
    if angle_degrees is None:
        raise ValueError("Input argument `angle_degrees` cannot be None.")
    
    try:
        angle_radians = radians(angle_degrees)
    except TypeError:
        raise ValueError("Input argument `angle_degrees` must be a number.")

    cosine_matrix = [
        [cos(angle_radians), -sin(angle_radians)],
        [sin(angle_radians),  cos(angle_radians)]
    ]
    return cosine_matrix




def calc_basic_rotation_3d(angle, axis=1):
    r"""
    Calculate a 3D rotation matrix about a basic axis.

    Parameters
    ----------
    angle : float
        Rotation angle in radians.
    axis : int, optional
        Axis about which the rotation is performed. Must be one of [1, 2, 3].
        Default is 1, meaning rotation about the x-axis.

    Returns
    -------
    rotation_matrix : array_like
        3x3 rotation matrix.

    Notes
    -----
    The rotation matrix is generated by permuting the elements of a basic 2D
    rotation matrix.

    Examples
    --------
    >>> calc_basic_rotation_3d(np.pi/2, axis=1)
    array([[1. , 0. , 0. ],
           [0. , 6.123233995736766e-17, 1. ],
           [0. , -1. , 6.123233995736766e-17]])
    """
    if angle is None:
        raise ValueError("Input argument `angle` cannot be None.")
    if axis is None:
        raise ValueError("Input argument `axis` cannot be None.")
    if axis not in [1, 2, 3]:
        raise ValueError("Input argument `axis` must be one of [1, 2, 3]")

    rotation_matrix = np.array([
        [1.0, 0.0, 0.0],
        [0.0, np.cos(angle), -np.sin(angle)],
        [0.0, np.sin(angle), np.cos(angle)]
    ])

    permutation_matrices = {
        2: np.array([
            [0.0, 1.0, 0.0],
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0]
        ]),
        3: np.array([
            [0.0, 0.0, 1.0],
            [1.0, 0.0, 0.0],
            [0.0, 1.0, 0.0]
        ])
    }
    if axis != 1:
        permutation_matrix = permutation_matrices[axis]
        rotation_matrix = permutation_matrix.T @ rotation_matrix @ permutation_matrix

    return rotation_matrix




def calculate_general_rotation_matrix(angles_radians, rotation_order=[1, 2, 3]):
    r"""
    Calculate the general rotation matrix.

    Parameters
    ----------
    angles_radians : list of float
        Three rotation angles in radians.
    rotation_order : list of int, optional
        The order of axis of the rotation operation. Default is [1, 2, 3].

    Returns
    -------
    rotation_matrix : numpy.array
        The general rotation matrix.

    Examples
    --------
    >>> rotation_matrix = calculate_general_rotation_matrix([np.pi/2, 0, 0])
    >>> np.round(rotation_matrix, 2)
    array([[0.  , 0.  , 1.],
           [0.  , 1.  , 0.],
           [-1. , 0.  , 0.]])
    """

    # Check validity of input arguments
    if angles_radians is None:
        raise ValueError("Input argument `angles_radians` cannot be None.")
    if not isinstance(angles_radians, (list, tuple)) or len(angles_radians) != 3:
        raise ValueError("`angles_radians` must be a list or tuple of three floats.")
    if not all(isinstance(angle, (int, float)) for angle in angles_radians):
        raise TypeError("Each angle in `angles_radians` must be an int or float.")

    if rotation_order is None:
        raise ValueError("Input argument `rotation_order` cannot be None.")
    if not isinstance(rotation_order, (list, tuple)) or len(rotation_order) != 3:
        raise ValueError("`rotation_order` must be a list or tuple of three integers.")
    if not all(axis in [1, 2, 3] for axis in rotation_order):
        raise ValueError("Each axis in `rotation_order` must be one of [1, 2, 3].")

    # Calculate the rotation matrix
    rotation_matrix = np.eye(3)
    for angle_radians, axis in zip(angles_radians, rotation_order):
        rotation_matrix_basic = calc_basic_rotation_3d(angle_radians, axis)
        rotation_matrix = np.dot(rotation_matrix_basic, rotation_matrix)

    return rotation_matrix




def rotate_vector_2d(vector_2d, angle_radians):
    r"""
    Rotate a 2D vector by a given angle.

    Parameters
    ----------
    vector_2d : list or tuple of float
        A 2D vector to be rotated.
    angle_radians : float
        The angle in radians to rotate the vector.

    Returns
    -------
    rotated_vector : list of float
        The rotated 2D vector.

    Examples
    --------
    >>> rotate_vector_2d([1, 0], np.pi/2)
    [0.0, 1.0]
    """
    if vector_2d is None:
        raise ValueError("Input argument `vector_2d` cannot be None.")
    if not isinstance(vector_2d, (list, tuple)) or len(vector_2d) != 2:
        raise ValueError("`vector_2d` must be a list or tuple of two floats.")
    if not all(isinstance(x, (int, float)) for x in vector_2d):
        raise TypeError("Each element in `vector_2d` must be an int or float.")
    if angle_radians is None:
        raise ValueError("Input argument `angle_radians` cannot be None.")
    if not isinstance(angle_radians, (int, float)):
        raise TypeError("`angle_radians` must be an int or float.")

    c = cos(angle_radians)
    s = sin(angle_radians)
    rotated_vector = [
        c * vector_2d[0] - s * vector_2d[1],
        s * vector_2d[0] + c * vector_2d[1]
    ]
    return rotated_vector




def calc_direction_cosine_matrix(a_basis, b_basis):
    r"""Calculate the direction cosine matrix between frame a and frame b.

    :math:`C_{ij} = a_i\ \cdot\ b_j`

    Parameters
    ----------
    a_basis : list of lists of float
        List of three a basis vectors (a1, a2, a3).
    b_basis : list of lists of float
        List of three b basis vectors (b1, b2, b3).

    Returns
    -------
    direction_cosine_matrix : list of lists of float
        3x3 matrix of the direction cosine.

    Examples
    --------
    >>> a_basis = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    >>> b_basis = [[1, 0, 0], [0, np.cos(np.pi/2), -np.sin(np.pi/2)], [0, np.sin(np.pi/2), np.cos(np.pi/2)]]
    >>> calc_direction_cosine_matrix(a_basis, b_basis)
    [[1.0, 0.0, 0.0],
     [0.0, 0.0, -1.0],
     [0.0, 1.0, 0.0]]
    """
    if a_basis is None or b_basis is None:
        raise ValueError("Input arguments `a_basis` and `b_basis` cannot be None.")
    if not all(isinstance(x, (list, tuple)) for x in a_basis):
        raise ValueError("Each element in `a_basis` must be a list or tuple.")
    if not all(isinstance(x, (list, tuple)) for x in b_basis):
        raise ValueError("Each element in `b_basis` must be a list or tuple.")
    if not all(isinstance(x, (int, float)) for row in a_basis for x in row):
        raise TypeError("Each element in `a_basis` must be an int or float.")
    if not all(isinstance(x, (int, float)) for row in b_basis for x in row):
        raise TypeError("Each element in `b_basis` must be an int or float.")
    if len(a_basis) != 3 or len(b_basis) != 3:
        raise ValueError("Input arguments `a_basis` and `b_basis` must have 3 elements each.")
    if not all(len(row) == 3 for row in a_basis):
        raise ValueError("Each row in `a_basis` must have 3 elements.")
    if not all(len(row) == 3 for row in b_basis):
        raise ValueError("Each row in `b_basis` must have 3 elements.")

    a_basis = np.array(a_basis)
    b_basis = np.array(b_basis)
    return a_basis @ b_basis.T





def rotation_matrix(axis, angle):
    r"""
    Returns the 3x3 rotation matrix for a rotation
    about 'axis' (must be length 3) by 'angle' (radians).

    Parameters
    ----------
    axis : list of float
        The axis of rotation.
    angle : float
        The angle of rotation in radians.

    Returns
    -------
    rotation_matrix : list of lists of float
        3x3 rotation matrix.

    Examples
    --------
    >>> rotation_matrix([1, 0, 0], np.pi/2)
    array([[1. , 0. , 0. ],
           [0. , 0. , -1. ],
           [0. , 1. , 0. ]])
    """
    axis = np.array(axis, dtype=float)
    axis = axis / np.linalg.norm(axis)
    x, y, z = axis
    c = np.cos(angle)
    s = np.sin(angle)
    t = 1 - c
    R = np.array([
        [t*x*x + c,   t*x*y - s*z, t*x*z + s*y],
        [t*x*y + s*z, t*y*y + c,   t*y*z - s*x],
        [t*x*z - s*y, t*y*z + s*x, t*z*z + c  ]
    ])
    return R




def rotate_stiffness_matrix(C, axis, angle_rad):
    r"""
    Rotate a 6x6 stiffness matrix using a rotation around an arbitrary axis.

    Parameters:
    - C: 6x6 stiffness matrix (2D array or list)
    - axis: 3-element list or array defining the rotation axis
    - angle_rad: rotation angle in radians

    Returns:
    - C_rot: rotated 6x6 stiffness matrix
    """
    C = np.array(C, dtype=np.float64)
    b = rotation_matrix(axis, angle_rad)

    # Construct 6x6 transformation matrix T for stiffness in Voigt notation
    R = np.zeros((6, 6))

    # Populate R using standard transformation rules
    for i in range(3):
        for j in range(3):
            R[i, j] = b[i, j]**2  # upper-left 3x3 block

    # Fill other transformation parts
    # upper-right 3x3 block
    R[0, 3] = 2*b[0, 1] * b[0, 2]
    R[0, 4] = 2*b[0, 0] * b[0, 2]
    R[0, 5] = 2*b[0, 0] * b[0, 1]

    R[1, 3] = 2*b[1, 1] * b[1, 2]
    R[1, 4] = 2*b[1, 0] * b[1, 2]
    R[1, 5] = 2*b[1, 0] * b[1, 1]

    R[2, 3] = 2*b[2, 1] * b[2, 2]
    R[2, 4] = 2*b[2, 0] * b[2, 2]
    R[2, 5] = 2*b[2, 0] * b[2, 1]

    # lower-left 3x3 block
    R[3, 0] = 2*b[1, 0] * b[2, 0]
    R[3, 1] = 2*b[1, 1] * b[2, 1]
    R[3, 2] = 2*b[1, 2] * b[2, 2]

    R[4, 0] = 2*b[2, 0] * b[0, 0]
    R[4, 1] = 2*b[2, 1] * b[0, 1]
    R[4, 2] = 2*b[2, 2] * b[0, 2]

    R[5, 0] = 2*b[0, 0] * b[1, 0]
    R[5, 1] = 2*b[0, 1] * b[1, 1]
    R[5, 2] = 2*b[0, 2] * b[1, 2]

    # lower-right 3x3 block
    R[3, 3] = b[1,1]*b[2,2] + b[1,2]*b[2,1]
    R[3, 4] = b[1,0]*b[2,2] + b[1,2]*b[2,0]
    R[3, 5] = b[1,0]*b[2,1] + b[1,1]*b[2,0]

    R[4, 3] = b[0,1]*b[2,2] + b[0,2]*b[2,1]
    R[4, 4] = b[0,0]*b[2,2] + b[0,2]*b[2,0]
    R[4, 5] = b[0,0]*b[2,1] + b[0,1]*b[2,0]

    R[5, 3] = b[0,1]*b[1,2] + b[0,2]*b[1,1]
    R[5, 4] = b[0,0]*b[1,2] + b[0,2]*b[1,0]
    R[5, 5] = b[0,0]*b[1,1] + b[0,1]*b[1,0]

    # Now rotate the stiffness matrix: C' = R C R^T
    C_rot = R @ C @ R.T
    return C_rot




def distance(p1: list, p2: list) -> float:
    r"""Compute the Euclidean distance between two 2D points.

    Parameters
    ----------
    p1 : list
        First point ``[x, y]``.
    p2 : list
        Second point ``[x, y]``.

    Returns
    -------
    float
        Euclidean distance between ``p1`` and ``p2``.
    """
    s2 = (p1[0] - p2[0])**2 + (p1[1] - p2[1])**2
    return sqrt(s2)




def ss(v1: list, v2: list, scale: list = None) -> float:
    r"""Compute the scaled sum of squared differences between two vectors.

    Parameters
    ----------
    v1 : list
        First vector.
    v2 : list
        Second vector, must have the same length as ``v1``.
    scale : list, optional
        Per-element scale factors. Defaults to ones (no scaling).

    Returns
    -------
    float
        Sum of ``(v1[i]*scale[i] - v2[i]*scale[i])**2`` over all elements.

    Raises
    ------
    ValueError
        If ``scale`` length does not match ``v1``.
    """
    if scale is None:
        scale = [1.] * len(v1)
    if len(scale) != len(v1):
        raise ValueError("`scale` length must match `v1`.")
    sumsqr = 0.0
    for i in range(len(v1)):
        sumsqr = sumsqr + (v1[i] * scale[i] - v2[i] * scale[i])**2
    return sumsqr




class Polynomial2DSP:
    r"""2D polynomial in two variables using the symmetric Pascal triangle basis.

    Parameters
    ----------
    order : int
        Maximum total degree of the polynomial.
    coeffs : array-like
        Coefficients ordered by total degree then by power of the second variable.
    """

    def __init__(self, order: int, coeffs) -> None:
        self.order = order
        self.coeffs = np.asarray(coeffs)

    def __call__(self, x) -> float:
        r"""Evaluate the polynomial at point ``x``.

        Parameters
        ----------
        x : array-like of length 2
            Evaluation point ``[x0, x1]``.

        Returns
        -------
        float
            Polynomial value at ``x``.
        """
        basis = []
        for i in range(self.order+1):
            for j in range(i+1):
                basis.append(x[0]**(i-j) * x[1]**j)
        basis = np.asarray(basis)
        return np.dot(self.coeffs, basis)




class PolynomialFunction:
    r"""1D polynomial function defined by coefficients or interpolation points.

    If ``x`` and ``y`` are provided, the coefficients are determined by solving
    the Vandermonde system so that the polynomial passes exactly through all
    given points. Otherwise ``coefficients`` are used directly.

    Parameters
    ----------
    coefficients : list, optional
        Polynomial coefficients ``[c0, c1, ..., cn]`` such that
        ``f(x) = c0 + c1*x + ... + cn*x**n``.
    x : list, optional
        x-coordinates of interpolation points.
    y : list, optional
        y-coordinates of interpolation points. Must have the same length as ``x``.
    """

    def __init__(self, coefficients=None, x=None, y=None) -> None:
        self.coefficients = coefficients if coefficients is not None else []
        self.points = {}
        x = x if x is not None else []
        y = y if y is not None else []
        if len(x) > 0:
            ndof = len(x)
            A = np.zeros((ndof, ndof))
            for i in range(ndof):
                self.points[x[i]] = y[i]
                for j in range(ndof):
                    A[i, j] = x[i]**j
            self.coefficients = np.linalg.solve(A, y)

    def __call__(self, x: float) -> float:
        r"""Evaluate the polynomial at ``x``.

        Parameters
        ----------
        x : float
            Evaluation point.

        Returns
        -------
        float
            Polynomial value at ``x``.
        """
        if x in self.points:
            return self.points[x]
        f = 0.0
        for i, c in enumerate(self.coefficients):
            f += c * x**i
        return f

    def __str__(self) -> str:
        terms = [f'({c})*x^{i}' for i, c in enumerate(self.coefficients)]
        return ' + '.join(terms)









def calc_coords_on_cylinder(X: list, r: float) -> list:
    r"""Map Cartesian coordinates to a cylindrical surface.

    Given a point ``X`` in the global inertial frame, return arc-length and
    axial coordinates on a cylinder of radius ``r`` whose axis is aligned with
    the z-direction (index 2).

    Parameters
    ----------
    X : list
        Coordinates ``[x, y, z]`` in the global inertial frame.
    r : float
        Radius of the cylinder.

    Returns
    -------
    list
        ``[arc_length, z]`` coordinates on the cylindrical surface.
    """
    x1 = r * atan2(X[1], X[0])
    x2 = X[2]
    return [x1, x2]


class FrameTransCylinder:
    r"""Callable that maps Cartesian coordinates to a cylindrical surface.

    The cylinder axis is aligned with the z-direction (index 2). For a point
    ``X = [x, y, z]``, the mapping is ``[r * atan2(y, x), z]``.

    Parameters
    ----------
    r : float
        Radius of the cylinder.
    """

    def __init__(self, r: float) -> None:
        self.r = r

    def __call__(self, X: list) -> list:
        r"""Map ``X`` to cylindrical surface coordinates.

        Parameters
        ----------
        X : list
            Cartesian coordinates ``[x, y, z]``.

        Returns
        -------
        list
            ``[arc_length, z]`` on the cylinder.
        """
        return [self.r * atan2(X[1], X[0]), X[2]]









def transform_rigid_3d(v0, R=None, t=None):
    r"""Transform a point/vector rigidly in 3D.

    Parameters
    ----------
    v0 : array-like of shape (3,)
        Input point or vector.
    R : array-like of shape (3, 3), optional
        Rotation matrix. Defaults to identity.
    t : array-like of shape (3,), optional
        Translation vector. Defaults to zero.

    Returns
    -------
    list
        Transformed point as a list of three floats.
    """
    v = np.asarray(v0)

    if R is None:
        R = np.eye(3)
    else:
        R = np.asarray(R)
    if t is None:
        t = np.zeros(3)
    else:
        t = np.asarray(t)

    v = np.dot(R, v) + t

    return v.tolist()




def _nonzero_abs_values(matrix: np.ndarray) -> np.ndarray:
    if matrix is None:
        raise ValueError("Input matrix cannot be None.")
    if not isinstance(matrix, np.ndarray):
        raise TypeError("Input must be a numpy array.")
    non_zero = matrix[matrix != 0]
    if non_zero.size == 0:
        raise ValueError("The matrix contains no non-zero values.")
    return non_zero


def find_min_nonzero_abs(matrix: np.ndarray) -> float:
    r"""Find the non-zero value with the smallest absolute value in a matrix.

    Parameters
    ----------
    matrix : np.ndarray
        A numpy array of any shape.

    Returns
    -------
    float
        The non-zero value with the smallest absolute value.

    Raises
    ------
    ValueError
        If the matrix is None or contains no non-zero values.
    TypeError
        If the input is not a numpy array.
    """
    non_zero = _nonzero_abs_values(matrix)
    return non_zero[np.argmin(np.abs(non_zero))]


def find_max_nonzero_abs(matrix: np.ndarray) -> float:
    r"""Find the non-zero value with the largest absolute value in a matrix.

    Parameters
    ----------
    matrix : np.ndarray
        A numpy array of any shape.

    Returns
    -------
    float
        The non-zero value with the largest absolute value.

    Raises
    ------
    ValueError
        If the matrix is None or contains no non-zero values.
    TypeError
        If the input is not a numpy array.
    """
    non_zero = _nonzero_abs_values(matrix)
    return non_zero[np.argmax(np.abs(non_zero))]
